apiVersion: v1
name: ae
version: 1.1.15
appVersion: 1.3.0
description: Official Gravitee.io Helm chart for Alert Engine
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
